### ISSUE TITLE
Allow custom color palette before writing to PDF. (Examples Dark Mode PDF)

### ISSUE THREAD

**Issue by siddhantladdha** [suuuehgi/noteshrunk#2]
Hi.
Consider this as a feature request, since I don't have any *fully working* code to support this request.
I processed a huge amount of data using noteshrink recently and wrote everything to a final PDF. My intent was to have a working copy of my notes as I further tinker with it. The aim is simple, to invert colors or customize colors.

The problem is that the scanned notes are "light mode" (they are written on White paper with Blue/Black and colored ink). However, when I like to read something digitally I like to use dark mode since it is easier on the eyes, plus I am a big fan of Dracula (A *universal* Dark theme). In some PDF readers you can invert the color however, this inversion does not work well for Scanned PDFs. In addition to that, I use [GoodNotes](https://www.goodnotes.com/) on my iPad, which does not support dark mode for PDF as of now. Any new notes that I take are Dracula color themed, and I personally hate the disconnect between my scanned and new notes. This is what started my exploration into this thing.

Now my mistake was deleting the images since I thought I could recover them successfully from the PDF using `pdftoppm` or `PyMupdf`. However, the images extracted from the PDF stop being indexed PNG and instead extract themselves as a RGBA image. (What I understood from all the googling was that the PDF runs its own compression so that the PDF size is almost the same as all the component PNGs. It is just the current tools extract it as a RGBA image, since saving to PDF might do that?) This means we are just inefficiently converting to and from the indexed version, even if there is no such need. Hence, I have currently given up on converting the RGBA image to indexed PNG and change the color palette.

**However, for people who would want such a feature, I recommend the best step is to apply this before the indexed PNG is written to the PDF file using `convert`**. Then they can invert the colors in HSL space. Why HSL? Since it maintains the correct color post inversion. This seems to be the approach apps like Nebo and Apple Notes take when they allow you to write documents in light and dark mode.

There is already a tool available [Invert PDF](https://invert-pdf.club/), but they seem to be inverting in RGB space instead of HSL space. (The color/hue is not preserved). Another tool [DarkPDF](https://github.com/merkez/darkpdf) seems to be doing the same thing (Inversion in RGB space) and also increasing the size. (4.9 MB PDF file became 14.8 MB).
 
I have a basic template that I tried using (code written with the help of ChatGPT). While it gave me perfect results in terms of image processing, I lost the indexed PNG aspect which exploded the output pdf size and that is officially the moment I gave up post-processing my pdf.

```
import fitz  # PyMuPDF
from PIL import Image, ImageOps
import io
import colorsys

def convert_to_indexed(image):
    """Convert an RGB image to an 8-color indexed image using an adaptive palette."""
    print("Converting image to 8-color indexed format...")
    image = image.convert('P', palette=Image.ADAPTIVE, colors=8)
    return image

def invert_luminance(image):
    """Invert the luminance of the image palette in HSL color space."""
    print("Inverting luminance of the image palette...")
    palette = image.getpalette()
    new_palette = []
    for i in range(0, len(palette), 3):
        r, g, b = palette[i:i+3]
        h, l, s = colorsys.rgb_to_hls(r / 255.0, g / 255.0, b / 255.0)
        l = 1 - l  # Invert luminance
        r, g, b = colorsys.hls_to_rgb(h, l, s)
        new_palette.extend([int(r * 255), int(g * 255), int(b * 255)])
    image.putpalette(new_palette)
    return image

def process_pdf_images(pdf_path, output_pdf_path):
    print(f"Opening PDF: {pdf_path}")
    doc = fitz.open(pdf_path)
    new_doc = fitz.open()  # Create a new document for output

    for page_num, page in enumerate(doc):
        print(f"Processing page {page_num + 1}...")
        image_list = page.get_images(full=True)
        for img_info in image_list:
            xref = img_info[0]
            base_image = doc.extract_image(xref)
            image_bytes = base_image['image']

            with Image.open(io.BytesIO(image_bytes)) as img:
                img = convert_to_indexed(img)
                img = invert_luminance(img)

                # Save the modified image to a bytes object
                img_byte_arr = io.BytesIO()
                img.save(img_byte_arr, format='PNG')
                img_byte_arr.seek(0)

                # Add a new page to the new document and insert the modified image
                new_page = new_doc.new_page(width=img.width, height=img.height)
                new_page.insert_image(new_page.rect, stream=img_byte_arr)

    print(f"Saving the modified PDF as {output_pdf_path}...")
    new_doc.save(output_pdf_path)
    doc.close()
    new_doc.close()
    print("Process completed successfully.")

# Usage
process_pdf_images('light.pdf', 'dark.pdf')
```

This approach can also be extended to using custom color schemes (like Dracula) the one I really want to convert to. For that, using indexed PNG is also preferred since it does not require you to go through the entire image and just allows doing a palette transformation per image.
This is important for speed, since such color transformation usually require minimum distance thresholding (where the threshold value is the color scheme colors). If you decide to integrate such feature, I would recommend you to use HSL or L*a*b colorspace to preserve the color correctness, but my intuition says that for indexed PNG, HSL will be good enough since we don't have smooth color gradients.

If you decide to integrate this feature into your code, you would have to apply `invert_luminance` as a post-processing step on the optimized PNG, **but** before writing to PDF.

Hope this helps.
Thanks!

**Comment by siddhantladdha** [comment]
I modified noteshrink to [noteshrink-dark](https://github.com/siddhantladdha/noteshrink-dark)
integrating the above changes.

**Comment by suuuehgi** [comment]
I'm not sure whether I got your questions ...

You want to

1. invert the colors and additionally
2. enforce a certain color scheme, like [Dracula](https://en.wikipedia.org/wiki/Dracula_(color_scheme))?

In any case, you can extract the images from a pdf using `pdfimages`. The PDF is just wrapper-fluff around the images.

**Comment by suuuehgi** [comment]
I made a quick test:

**Inverted RGB**
![inverted](https://github.com/suuuehgi/noteshrunk/assets/7861774/3d0d2aec-54bb-4659-8c22-dea6024c8d44)


Inverted RGB mapped to [Dracula](https://en.wikipedia.org/wiki/Dracula_(color_scheme)#Color_palette)
![dracula_delta](https://github.com/suuuehgi/noteshrunk/assets/7861774/0ac3f308-9af5-4c9a-931f-bc368b98bbb1)

**Comment by siddhantladdha** [comment]
Looks lovely!! Please add the option to integrate if you can. While I have already created something which does this, It would always be good if people have options.
Thanks.
Feel free to close the issue.

**Comment by suuuehgi** [comment]
Yeah, maybe I'll add that ... But it's kind of a specialized feature. I don't want to clutter the program with features few people use. Let's see ...

As you already wrote your own version and I don't need that functionality, it's rather on the low priority side.

**Comment by siddhantladdha** [comment]
cool. no worries.
